language: generic 
sudo: required
services:
 - docker

before_install:
 - docker build -t partha2020/mulit-test -f ./client/Dockerfile.dev ./client

after_success:
 - docker build -t partha2020/mulit-client ./client
 - docker build -t partha2020/mulit-nginx ./nginx
 - docker build -t partha2020/mulit-server ./server
 - docker build -t partha2020/mulit-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push partha2020/mulit-client
 - docker push partha2020/mulit-nginx
 - docker push partha2020/mulit-server
 - docker push partha2020/mulit-worker
 
deploy:
 edge: true
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "multi-docker"
 env: "MultiDocker-env"
 bucket_name: "elasticbeanstalk-us-east-2-531107532671"
 bucket_path: "multi-docker"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY